### PR TITLE
Document update_limits! and others

### PR DESCRIPTION
**Pull request by asinghvi17**
The aim is to have documentation on how `update_limits!` works, without having to look into the source code.  Hopefully this can be built into future documentation!

### CODE REVIEW

**Comment by asinghvi17** [comment]
This should be pretty much done in terms of functionality, now it's all MakieGallery :D

**Comment by asinghvi17** [comment]
Nevermind, not ready for review!

**Comment by asinghvi17** [comment]
Sorry for all the waffling - diff looked really weird.  It's much better now :)...merge at your convenience!

**Comment by SimonDanisch** [comment]
Thank you, looks great :)

**Pull request merged**
