### PR TITLE
Add showlibrary as a function

### PR DESCRIPTION
**Pull request by asinghvi17**
Adds a recipe `showlibrary` to show a color library.

### CODE REVIEW

**Comment by asinghvi17** [comment]
The recipe approach is yielding a couple of problems, I'll just make it a function and export.

```
using Makie
showlibrary(:colorcet)
```

yields

Screen Shot 2019-04-12 at 1 43 05  77400PM

**Comment by mkborregaard** [comment]
@SimonDanisch why is Travis testing on Julia 0.6?

**Comment by mschauer** [comment]
We can also sort them into a rainbow.

**Comment by mkborregaard** [comment]
Absolutely, that's just more work :-D

**Comment by mkborregaard** [comment]
Smaller fontsize would be nice too

**Comment by asinghvi17** [comment]
That's the default Travis script (which is broken anyway).  The branch sd-testci has the actual latest CI.

**Comment by asinghvi17** [comment]
Now, it looks like this:

**Comment by asinghvi17** [comment]
Should be ready for merge!  The result of this PR is creating two user-facing functions, `showgradients` and `showlibrary`.  

`showgradients` takes in an Array of Symbols, and returns a Scene of the associated colourmaps.

`showlibrary` takes in a single Symbol representing the Library to be shown, and calls `showgradients` on a sorted Array of the colormaps of that library.

**Comment by SimonDanisch** [comment]
Thanks you, that's lovely :)

**Comment by mkborregaard** [comment]
Very very nice!

**Comment by mschauer** [comment]
> Absolutely, that's just more work :-D

Only a little bit...
```
using Colors, HilbertSpaceFillingCurve
const F8 = Colors.N0f8
n = 100
cols = [RGB{F8}((rand(F8), rand(F8), rand(F8))...) for i in 1:n]
ii = sortperm([hilbert(reinterpret.(UInt8, [c.r,c.g,c.b]) , 3, 8) for c in cols])
scatter(1:n,1:n, markersize=2.,  color=cols[ii])
```
following the Hilbert-curve approach on https://www.alanzucconi.com/2015/09/30/colour-sorting/ "The incredibly challenging task of sorting colours" (sic! :-D).

**Comment by mkborregaard** [comment]
Sweet - how does that look for colorcet?

**Comment by asinghvi17** [comment]
I sorted by the first element of each colormap - of course, one *could* sort by the middle element or something, but I was kind of lazy :P 

```julia
using Makie, HilbertSpaceFillingCurve, PlotUtils

clibrary(:colorcet)

grads = PlotUtils.cgradients(:colorcet)

cols = PlotUtils.cgrad.(grads) .|> x -> x[1]

ii = sortperm([hilbert(reinterpret.(Int, [c.r,c.g,c.b]), 3, 8) for c in cols])

showgradients(grads[ii])

```

Screen Shot 2019-04-17 at 6 54 18  61600PM

Looks interesting, but I must say the alphabetical sorting is probably easier for reference!

**Comment by mschauer** [comment]
You are sorting the reinterpreted `Float64`s. Can you include a step
```
cols = RGB{Colors.N0f8}.(cols)
```
and show the results?

**Comment by asinghvi17** [comment]
```julia
julia> ii = sortperm([hilbert(reinterpret.(Int, [c.r,c.g,c.b]), 3, 8) for c in cols])
ERROR: bitcast: expected primitive type value for second argument
Stacktrace:
 [1] reinterpret at ./essentials.jl:381 [inlined]
 [2] _broadcast_getindex_evalf at ./broadcast.jl:578 [inlined]
 [3] _broadcast_getindex at ./broadcast.jl:561 [inlined]
 [4] getindex at ./broadcast.jl:511 [inlined]
 [5] macro expansion at ./broadcast.jl:843 [inlined]
 [6] macro expansion at ./simdloop.jl:73 [inlined]
 [7] copyto! at ./broadcast.jl:842 [inlined]
 [8] copyto! at ./broadcast.jl:797 [inlined]
 [9] copy at ./broadcast.jl:773 [inlined]
 [10] materialize at ./broadcast.jl:753 [inlined]
 [11] (::getfield(Main, Symbol("##15#16")))(::RGB{FixedPointNumbers.Normed{UInt8,8}}) at ./none:0
 [12] iterate at ./generator.jl:47 [inlined]
 [13] collect(::Base.Generator{Array{RGB{FixedPointNumbers.Normed{UInt8,8}},1},getfield(Main, Symbol("##15#16"))}) at ./array.jl:606
 [14] top-level scope at none:0
```
after adding the recommended step.

**Comment by SimonDanisch** [comment]
You need to change the int type to e.g. Int8

**Comment by mschauer** [comment]
Screenshot 2019-04-24 at 10 31 34

**Comment by mkborregaard** [comment]
Hm. I'm not convinced that's better than alphabetical.
If we do show them in any logical order, it should at least be divided into sequential (monochromatic/singlechromatic), divergent and cyclic gradients. That makes much more sense for the user than by the starting color.

**Comment by mschauer** [comment]
No, we shouldn't do anything here, I just needed to see it.

**Pull request merged**
