### PR TITLE
Try to fix StaticArrays depwarn

### PR DESCRIPTION
**Pull request by asinghvi17**
@SebastianM-C would you mind trying this out and seeing whether it fixes the depwarn in your screenshot from Slack?

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Is that the only one? I thought there might have been more...

**Comment by asinghvi17** [comment]
That's the only one I saw...there might be more.  Will check fully later...

**Comment by SimonDanisch** [comment]
Well, if the warnings are gone, it should be fine I guess... ;)

**Comment by SebastianM-C** [comment]
With
```julia
using AbstractPlotting, GLMakie

scatter(rand(3),rand(3),rand(3))
```
I still get some depwarns
```
┌ Warning: `a::StaticArray + b::Number` is deprecated, use `a .+ b` instead.
│   caller = (::getfield(AbstractPlotting, Symbol("##49#50")){AbstractPlotting.TextureAtlas,Char,Array{Ptr{FreeType.FT_FaceRec},1}})() at texture_atlas.jl:186
└ @ AbstractPlotting ~/.julia/dev/AbstractPlotting/src/utilities/texture_atlas.jl:186
┌ Warning: `a::StaticArray - b::Number` is deprecated, use `a .- b` instead.
│   caller = (::getfield(AbstractPlotting, Symbol("##49#50")){AbstractPlotting.TextureAtlas,Char,Array{Ptr{FreeType.FT_FaceRec},1}})() at texture_atlas.jl:186
└ @ AbstractPlotting ~/.julia/dev/AbstractPlotting/src/utilities/texture_atlas.jl:186
┌ Warning: `a::StaticArray + b::Number` is deprecated, use `a .+ b` instead.
│   caller = + at operators.jl:529 [inlined]
└ @ Core ./operators.jl:529
```

**Comment by asinghvi17** [comment]
@SimonDanisch I don't have the bandwidth to figure out why Gitlab keeps failing...would you mind taking a look at it whenever you get the time?  Thanks!

**Comment by asinghvi17** [comment]
I think that the resolver needed a little help.   Seems to be past that stage now.

**Comment by SebastianM-C** [comment]
The error on Gitlab seems to be from failing to build FFMPEG (possibly due to a network error indicated by `curl: (7) Failed to connect to github.com port 443: Connection timed out`).

**Comment by asinghvi17** [comment]
Yeah, that's the next step I have to debug :D - before this, there was a consistent version conflict popping up, which was resolved by pinning StaticArrays to 0.11.

**Comment by asinghvi17** [comment]
ah.  Something weird is going on with platform keys:
```
┌ Error: Error building `Rmath`: 
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ ┌ Warning: Could not extract the platform key of https://github.com/staticfloat/RmathBuilder/releases/download/v0.2.0-1/libRmath.x86_64-linux-gnu.tar.gz; continuing...
│ └ @ BinaryProvider /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/BinaryProvider/kcGxO/src/Prefix.jl:185
│ [ Info: Downloading https://github.com/staticfloat/RmathBuilder/releases/download/v0.2.0-1/libRmath.x86_64-linux-gnu.tar.gz to /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/Rmath/4wt82/deps/usr/downloads/libRmath.x86_64-linux-gnu.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/staticfloat/RmathBuilder/releases/download/v0.2.0-1/libRmath.x86_64-linux-gnu.tar.gz to /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/Rmath/4wt82/deps/usr/downloads/libRmath.x86_64-linux-gnu.tar.gz:
```

**Comment by SimonDanisch** [comment]
Thank you! Lets fix the tests another time -.-

**Pull request merged**
