### PR TITLE
[WIP] add more themability to Axis3d

### PR DESCRIPTION
**Pull request by asinghvi17**
This PR aims to make it possible to theme an Axis3d similarly to an Axis2d, where the grid can have a linestyle.  This will make it easier to theme them and allow for 'less visible' grid lines in Themes.

This PR is related to JuliaPlots/MakieThemes.jl#10, and must be merged into master before its functionality can work.

TODO list (help wanted):
- [ ] Change API for Axis3D to be consistent with Axis2d (frames v/s grid)
- [ ] Determine which keyword attributes to include
- [x] Look into using `optimize_ticks`
- [ ] Add a tick formatter argument, so that you can have scientific ticks (first step to log scales?)

### CODE REVIEW

**Comment by asinghvi17** [comment]
Another possibility is to integrate the `optimize_ticks` functions from PlotUtils into this...

**Comment by SimonDanisch** [comment]
>Another possibility is to integrate the optimize_ticks functions from PlotUtils into this...

I already do that for axis2D... and I thought for 3D as well?

**Comment by SimonDanisch** [comment]
Yup: https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/basic_recipes/axis.jl#L232

**Comment by asinghvi17** [comment]
Huh...this shouldn't be happening though, right?

**Comment by SimonDanisch** [comment]
what part? Looks ok to me at first sight!

**Comment by asinghvi17** [comment]
Oh, it doesn't take the origin into account.  I had thought that optimize_ticks would also optimize placement of the origin (some of the axis gridlines are pretty close to it...




Sincerely,




Anshul Singhvi.







On Sun, Apr 14, 2019 at 3:57 PM -0400, "Simon" <notifications@github.com> wrote:












what part? Looks ok to me at first sight!

**Comment by SimonDanisch** [comment]
Nope, that's unrelated ;)

**Comment by asinghvi17** [comment]
Hmm, makes sense...I guess it was something weird with that particular set of random numbers :P

**Comment by asinghvi17** [comment]
Some discussion in #91, for support of Unitful

**Comment by asinghvi17** [comment]
Following discussion in Slack, the Axis3d and Axis2d Themes should be made consistent.

**Comment by asinghvi17** [comment]
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/a383b420e943f85df7135c18a873bc93e8de24f6/src/basic_recipes/axis.jl#L134-L138

**Comment by asinghvi17** [comment]
Note to self: Try to look into PGFPlots styling for this stuff

**Comment by asinghvi17** [comment]
Closing in favour of a new PR, to come later...

**Pull request closed without merging**
