### PR TITLE
remove all the Observable conversion clutter

### PR DESCRIPTION
**Pull request by SimonDanisch**
Needs: https://github.com/JuliaGizmos/Observables.jl/pull/40

### CODE REVIEW

**Comment by asinghvi17** [comment]
I don't think Observables reexports the new stuff yet.

**Comment by SimonDanisch** [comment]
It shouldn't need to, I think^^
Did you remove most usage of `push!` from makiegallery?

**Comment by asinghvi17** [comment]
Yeah, the only uses of it were in the tutorials anyway...we may not import the functions from Observables explicitly, though.

**Pull request merged**
