### PR TITLE
test with MakieGallery

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by asinghvi17** [comment]
Shall we also use Gitlab CI within AbstractPlotting.jl to test rendering?  Perhaps an environment variable could be set?

**Comment by asinghvi17** [comment]
Also, I think you might have to regenerate the reference images.

**Comment by asinghvi17** [comment]
Should we merge this now?  Seems like it works.

**Comment by SimonDanisch** [comment]
Thank you :)

**Pull request merged**
