### PR TITLE
add tests for @lift macro

### PR DESCRIPTION
**Pull request by jkrumbiegel**

### CODE REVIEW

**Comment by asinghvi17** [comment]
@jkrumbiegel this is unrelated, but do you know what might be causing this?
```julia
  UndefVarError: width not defined
  Stacktrace:
   [1] (::AbstractPlotting.MakieLayout.var"#311#321")(::NTuple{4,Float32}, ::GeometryBasics.HyperRectangle{2,Int64}) at ./none:0
   [2] lift(::Function, ::Observable{Any}, ::Observable{GeometryBasics.HyperRectangle{2,Int64}}) at /home/travis/build/JuliaPlots/AbstractPlotting.jl/src/interaction/nodes.jl:8
   [3] LLegend(::Scene, ::Observable{Array{Tuple{Union{Nothing, String},Array{LegendEntry,1}},1}}; bbox::Nothing, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/travis/build/JuliaPlots/AbstractPlotting.jl/src/makielayout/lobjects/llegend.jl:34
   [4] LLegend at /home/travis/build/JuliaPlots/AbstractPlotting.jl/src/makielayout/lobjects/llegend.jl:6 [inlined]
   [5] LLegend(::Scene, ::Array{Scatter{...},1}, ::Array{String,1}, ::Nothing; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/travis/build/JuliaPlots/AbstractPlotting.jl/src/makielayout/lobjects/llegend.jl:426
   [6] LLegend at /home/travis/build/JuliaPlots/AbstractPlotting.jl/src/makielayout/lobjects/llegend.jl:420 [inlined] (repeats 2 times)
   [7] top-level scope at /home/travis/build/JuliaPlots/AbstractPlotting.jl/test/runtests.jl:18
```

**Comment by jkrumbiegel** [comment]
I was using the functions `width` and `height` for 2D rectangles, it seems that `width` is not found. Maybe Simon didn't copy it? I could just replace it with `widths(rect)[1]` but I liked the explicitness of `height` and `width` for normal rectangles

**Comment by asinghvi17** [comment]
It's possible they weren't copied, I can't see their definitions anywhere.

**Comment by jkrumbiegel** [comment]
aha now I know what's wrong, it's a macro hygiene problem. It seems that the lift macro used inside the `MakieLayout` submodule scopes all variables as `AbstractPlotting.variable`. That's why it doesn't see the functions imported within MakieLayout.. I'm still trying to understand how to remedy this.

**Pull request merged**
