### PR TITLE
Remove ImageMagick

### LINKED ISSUE #381: ImageMagick ?
from a quick glance, AbstractPlotting imports but never uses `ImageMagick`. Can it be removed?

### PR DESCRIPTION
**Pull request by asinghvi17**
Fixes #381

### CODE REVIEW

**Comment by asinghvi17** [comment]
Wow, this should cut 4 seconds off load time 😮

**Comment by asinghvi17** [comment]
Do we need this anywhere?  CI passes, but I'm still not 100% sure we can remove this.

**Comment by asinghvi17** [comment]
Travis didn't report the check status, but manually checking confirms it's green.

**Comment by SimonDanisch** [comment]
You should try this locally without MakieGallery, since MakieGallery also brings in ImageMagick!
It's sadly currently needed for FileIO to work:
```julia
julia> scatter(1:4)
Error encountered while loading "/home/s/MakieDev/dev/AbstractPlotting/assets/icons/line-graph-128.bmp".

Fatal error:
Error showing value of type Scene:
ERROR: ArgumentError: Package ImageMagick not found in current path:
- Run `import Pkg; Pkg.add("ImageMagick")` to install the ImageMagick package.
```
We would need to remove all image loading from AbstractPlotting to remove ImageMagick

**Comment by asinghvi17** [comment]
Dang, that puts a damper on things.  I suppose we could save images as delimited files or CSV...

**Comment by SimonDanisch** [comment]
Yeah or as binary, like i do in glmakie!

**Comment by SimonDanisch** [comment]
https://github.com/JuliaPlots/GLMakie.jl/blob/master/src/screen.jl#L281

**Pull request closed without merging**
