### PR TITLE
add formatter kwarg to title

### LINKED ISSUE #272: Support Dates for `title` or more generally for whatever textbox
```
julia> times[1]
2000-03-15

julia> titletext = Node(times[1])
Observable{Date} with 0 listeners. Value:
2000-03-15

julia> fullsc = title(scene, titletext; fontsize = 40)
ERROR: MethodError: no method matching boundingbox(::Text{...}, ::Date)
Closest candidates are:
  boundingbox(::Text{...}) at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\boundingbox.jl:97
  boundingbox(::Union{Text{...}, MeshScatter{...}, Scatter{...}, Mesh{...}, LineSegments{...}, Lines{...}, Surface{...}, Volume{...}, Heatmap{...}, Image{...}} where Arg) at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\boundingbox.jl:41        
  boundingbox(::Text{...}, ::String) at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\boundingbox.jl:86
  ...
Stacktrace:
 [1] boundingbox(::Text{...}) at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\boundingbox.jl:97
 [2] raw_boundingbox(::Array{AbstractPlotting.Transformable,1}) at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\boundingbox.jl:71
 [3] raw_boundingbox(::Scene) at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\boundingbox.jl:59
 [4] boundingbox at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\boundingbox.jl:45 [inlined]
 [5] layout_sizes(::Array{Scene,1}, ::Vec{2,Int64}, ::Int64) at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\layouting.jl:294
 [6] #587 at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\layouting.jl:228 [inlined]
 [7] lift at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\interaction\nodes.jl:9 [inlined]
 [8] #layout#586(::Scene, ::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(AbstractPlotting.layout), ::Array{Scene,1}, ::Int64) at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\layouting.jl:228
 [9] #hbox at .\none:0 [inlined]
 [10] #hbox#583(::Base.Iterators.Pairs{Symbol,Scene,Tuple{Symbol},NamedTuple{(:parent,),Tuple{Scene}}}, ::typeof(hbox), ::Scene, ::Vararg{Scene,N} where N) at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\layouting\layouting.jl:206
 [11] (::AbstractPlotting.var"#kw##hbox")(::NamedTuple{(:parent,),Tuple{Scene}}, ::typeof(hbox), ::Scene, ::Scene) at .\none:0
 [12] #title#709(::Tuple{Symbol,Symbol}, ::Int64, ::Scene, ::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:fontsize,),Tuple{Int64}}}, ::typeof(title), ::Scene, ::Observables.Observable{Date}) at C:\Users\datse\.julia\packages\AbstractPlotting\3uXXp\src\basic_recipes\title.jl:23
 [13] (::AbstractPlotting.var"#kw##title")(::NamedTuple{(:fontsize,),Tuple{Int64}}, ::typeof(title), ::Scene, ::Observables.Observable{Date}) at .\none:0
 [14] top-level scope at none:0
```

I guess the way to solve this is to always convert whatever the user gives to a textbox by calling `string(arg)` ? In any case, I'd like to contribute the solution to this if someone guides me on where to start.

### PR DESCRIPTION
**Pull request by asinghvi17**
fix #272

cc @Datseris

### CODE REVIEW

**Comment by Datseris** [comment]
If I want to change the title later interactively, is it enough to make the input `tstring` an Observable, whose value I can later change?

**Comment by asinghvi17** [comment]
Yeah, that's fine I think

**Comment by asinghvi17** [comment]
oh god, gitlab is failing again

**Comment by Datseris** [comment]
Shouldn't similar functionality as this also apply in `text` (a function that just puts a text somewhere, I guess such a function exists) and all derivatives? Maybe it is even possible to make it in a unified way?

At the moment I don't immediately see the benefits of having a dedicated formatter kwarg... users should/could add a method to `string` for custom types. Perhaps you can reduce complexity by using string directly?

**Comment by asinghvi17** [comment]
I don't know if that makes sense for all text - what if you input a Vector{Point2f0} by accident, and it's not caught?  It's pretty easy to just set up an Observable to convert whatever you have into a String, and it allows greater flexibility for sure.

**Comment by SimonDanisch** [comment]
> oh god, gitlab is failing again

You need to filter out the diffeq example: https://github.com/JuliaPlots/MakieGallery.jl/blob/master/test/runtests.jl#L40

**Pull request merged**
