### PR TITLE
allow passing of arbitrary kwargs to textslider

### PR DESCRIPTION
**Pull request by asinghvi17**
also, capture some of them

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Thank you!

**Comment by asinghvi17** [comment]
I don't know if that actually works :D...shouldn't break anything though

**Comment by mschauer** [comment]
I'll test later

**Comment by mschauer** [comment]
It doesn't seem to work, compare
```
s2, _ = textslider(0.0f0:0.001f0:3.0f0, "blah", start = 0.3, textcolor=:white, slidercolor=:white, buttonstrokecolor = :white); display(s2)
```
with 
```
s2 = Scene(camera = campixel!, backgroundcolor=(:blue, 0.8)); s2 = slider!(s2, 0.0f0:0.001f0:3.0f0, raw=true, start = 0.3, textcolor=:white, slidercolor=:white, buttonstrokecolor = :white)
```

**Comment by mschauer** [comment]
@SebaGraz

**Pull request merged**
