### PR TITLE
move docs from makiegallery to abstractplotting

### PR DESCRIPTION
**Pull request by jkrumbiegel**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Yay :)

**Review by SimonDanisch — APPROVED** [review]

**Comment by MichaelHatherly** [comment]
Hey @jkrumbiegel @SimonDanisch, I came across your `Gitlab <: Documenter.DeployConfig` implementation when trying to solve the same problem with the Pumas docs (since they also get built on gitlab and hosted on github). Would you be interested in upstreaming this into Documenter rather than us having to re-implement it multiple times? If you've not got the time to PR I'm happy to do the work upstreaming it myself.

**Comment by jkrumbiegel** [comment]
Would be cool if Documenter had this functionality, I was just not sure if it's "mainstream" enough of an approach? That's why I didn't make a PR, but you're welcome to do that!

**Comment by MichaelHatherly** [comment]
I'll make a PR then, and we can see if two is mainstream enough.

**Pull request merged**
