### PR TITLE
Add a compression factor option to `record`

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
Could someone test this, to see if it works correctly?

**Comment by SimonDanisch** [comment]
Did you test it with a couple of examples?

**Comment by asinghvi17** [comment]
I tested it, but am not sure if it works.  Will try on a really large example using CairoMakie.

**Comment by asinghvi17** [comment]
Here's a zipfile with several videos.  For high resolutions, you can see the effect of compression.
https://drive.google.com/open?id=1FVITSTaI9kRUqmbqxX5RVSM7LTrKqNhd

**Pull request merged**
