### PR TITLE
Prepare a release

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
argh, this pkg crap again

**Comment by asinghvi17** [comment]
The orthographic camera does actually fail, but the rest of the examples look fine.
Refimage:
ref_image
Testimage:
test_image

**Comment by SimonDanisch** [comment]
that looks fine :)

**Comment by ffreyer** [comment]
Probably a result of the updates to light calculations. Running the example with
```julia
scene = mesh(merge(meshes), ambient=Vec3f0(0.03), specular=Vec3f0(0.3), diffuse=Vec3f0(0.9), lightposition=Vec3f0(20))
```
to restore the previous values gives

Screenshot from 2020-03-24 01-12-08

This shouldn't be/isn't exactly the same because the way `o_vertex ` is calculated in the shader has changed.

**Comment by asinghvi17** [comment]
@SimonDanisch should we go ahead and tag AbstractPlotting + GLMakie?

**Comment by piever** [comment]
StatsMakie master branch at the moment relies on some features that only exist on AbstractPlotting master, it'd be great to tag here so that I can add a lower bound and tag there as well.

**Comment by asinghvi17** [comment]
I'm re-running Gitlab now; if it passes, I'll releaase.

**Pull request closed without merging**
