### PR TITLE
Pass kwargs to `backend_show` in `save`

### PR DESCRIPTION
**Pull request by asinghvi17**
I'm not sure whether this is the right way to do this, but it seems to make sense...

### CODE REVIEW

**Comment by SimonDanisch** [comment]
what's the use case? We should add tests + examples for this ;)

**Comment by asinghvi17** [comment]
The original usecase for this was the ability to change the DPI when rendering PNGs in CairoMakie (you can read an in-memory SVG into Rsvg, which can then render to an upscaled PNG).

**Comment by SimonDanisch** [comment]
Well this needs to be documented then...and best write out the keyword arguments ;)
Like it is right now, its impossible to know what this is for, why its there and how one can use it.

**Comment by SimonDanisch** [comment]
Closing for now, feel free to reopen once we have some clear direction / docs for this!

**Comment by asinghvi17** [comment]
@jkrumbiegel has a way to render arbitrary-DPI raster images in CairoMakie, so we could document this directly in the CairoMakie README.  This would also allow, e.g., metadata forwarding for PDF.

**Comment by SimonDanisch** [comment]
Implemented by #407

**Pull request closed without merging**
