### PR TITLE
Button tweaks

### PR DESCRIPTION
**Pull request by grero**
As I was playing around with the buttons part of the GUI tools, I noticed a few short comings. This is my attempts at rectifying some of them.

### CODE REVIEW

**Comment by asinghvi17** [comment]
@grero would you say this is finished?

**Comment by grero** [comment]
Hm, I'd say it implements want I needed for my particular use, but I defer to you experts whether it's worth merging in its current state : )

**Comment by asinghvi17** [comment]
Well, if there aren't any other changes you'd like to make, we may as well - and more pull requests can always be made for new features :)

**Comment by SimonDanisch** [comment]
Thank you, that looks good :)

**Pull request merged**
