### PR TITLE
Ffreyer docs

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
@ffreyer, non commiters don't get a preview :( 
But here you are: http://makie.juliaplots.org/previews/PR626/lighting.html
Is this really with SSAO?
image

**Comment by ffreyer** [comment]
No :(

This is how it looks when I run it manually:
Screenshot from 2021-02-04 00-29-21

**Comment by ffreyer** [comment]
`GLMakie.enable_SSAO[] = true` requires shaders to recompile, maybe that's causing an issue?

**Comment by SimonDanisch** [comment]
that could be...maybe we need to close(current_screen()) somewhere

**Comment by SimonDanisch** [comment]
Alright, that worked... can you check if this looks good to you? http://makie.juliaplots.org/previews/PR626/lighting.html
And @jkrumbiegel I saw you discussed the changes introduced here on slack and am not sure what the conclusion was...Could you give your approval?

**Comment by ffreyer** [comment]
The ssao plot looks good now.

I did a few tests with the change like I described in the original pr, they all looked normal. Maybe there are some edge cases where this changes something, but then you can just use `LScene(scenekw = (clear=false, ))` to get the old behavior back. I think it's fine.

**Review by jkrumbiegel — APPROVED** [review]
I think it's fine, we'll see if the clearing trips a lot of people up when other things overlap, I guess

**Pull request merged**
