### PR TITLE
basic unit support for markersize

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Needs: https://github.com/JuliaRegistries/General/pull/2377

**Comment by c42f** [comment]
The following behavior concerns me a bit:

```
julia> using AbstractPlotting
julia> 1mm + 1dip
AbstractPlotting.Millimeter{Int64}(2)
```

This seems inherent in the way that `AbstractNumbers` currently works with the `like` function taking the first argument in binary operations.

Can `Unitful` be made to work for what you're doing? I've got a bit of experience with that codebase so I might be able to provide some insight if you've got specific problems with it.

**Comment by mkborregaard** [comment]
what happened to this nice pr?

**Comment by SimonDanisch** [comment]
I merged a simpler version: https://github.com/JuliaPlots/AbstractPlotting.jl/pull/257/files
so `markersize=20px` should work now...

**Comment by mkborregaard** [comment]
oh sweet :heart:

**Comment by mkborregaard** [comment]
Doesn't work on Vectors though?

**Pull request closed without merging**
