### PR TITLE
WIP autocomplete for getproperty 

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Does this work?

**Comment by asinghvi17** [comment]
Not yet, I might need fieldnames instead - let me experiment for a couple minutes and get back to you...

**Comment by SimonDanisch** [comment]
Maybe it's not possible?

**Comment by asinghvi17** [comment]
Possibly not, I can't see any way to do it.  Oh well, maybe later...

**Pull request closed without merging**
