### PR TITLE
Fix conversion for a function on an interval

### PR DESCRIPTION
**Pull request by piever**

### CODE REVIEW

**Comment by asinghvi17** [comment]
Needs a MakieGallery test (possibly also one in AbstractPlotting)

**Comment by piever** [comment]
I'm not too sure how MakieGallery works, but I can definitely add tests for the conversion here in AbstractPlotting.

**Comment by asinghvi17** [comment]
I've added some small tests in JuliaPlots/MakieGallery.jl#213

**Comment by asinghvi17** [comment]
Will wait for Gitlab, then merge.  That should also be the first test of dynamic refimage update.

**Comment by piever** [comment]
Thanks! Could you also tag a patch release afterwards? That way I can tag StatsMakie

**Pull request merged**
