### PR TITLE
Update Stepper documentation, allow custom format

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
needs tests in Gallery

**Comment by asinghvi17** [comment]
> ┌ Warning: No OpenGL detected!  Software tests only.
└ @ Main /builds/JuliaGPU/AbstractPlotting-jl/test/runtests.jl:9

wat

**Comment by asinghvi17** [comment]
@SimonDanisch this seems to be the stacktrace for a GLMakie build error in GItlab:
```julia
┌ Error: Error building `GLFW`: 
│ -- The C compiler identification is GNU 7.4.0
│ -- Check for working C compiler: /usr/bin/cc
│ -- Check for working C compiler: /usr/bin/cc -- works
│ -- Detecting C compiler ABI info
│ -- Detecting C compiler ABI info - done
│ -- Detecting C compile features
│ -- Detecting C compile features - done
│ -- Looking for pthread.h
│ -- Looking for pthread.h - found
│ -- Looking for pthread_create
│ -- Looking for pthread_create - not found
│ -- Looking for pthread_create in pthreads
│ -- Looking for pthread_create in pthreads - not found
│ -- Looking for pthread_create in pthread
│ -- Looking for pthread_create in pthread - found
│ -- Found Threads: TRUE  
│ -- Using X11 for window creation
│ -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
│ -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
│ -- Looking for gethostbyname
│ -- Looking for gethostbyname - found
│ -- Looking for connect
│ -- Looking for connect - found
│ -- Looking for remove
│ -- Looking for remove - found
│ -- Looking for shmat
│ -- Looking for shmat - found
│ -- Looking for IceConnectionNumber in ICE
│ -- Looking for IceConnectionNumber in ICE - found
│ -- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
│ -- Configuring done
│ -- Generating done
│ -- Build files have been written to: /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/usr/downloads/src/build
│ Scanning dependencies of target glfw
│ [  5%] Building C object src/CMakeFiles/glfw.dir/context.c.o
│ In file included from /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/usr/downloads/src/src/internal.h:187:0,
│                  from /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/usr/downloads/src/src/context.c:28:
│ /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/usr/downloads/src/src/x11_platform.h:48:10: fatal error: X11/extensions/XInput2.h: No such file or directory
│  #include <X11/extensions/XInput2.h>
│           ^~~~~~~~~~~~~~~~~~~~~~~~~~
│ compilation terminated.
│ src/CMakeFiles/glfw.dir/build.make:62: recipe for target 'src/CMakeFiles/glfw.dir/context.c.o' failed
│ make[2]: *** [src/CMakeFiles/glfw.dir/context.c.o] Error 1
│ CMakeFiles/Makefile2:122: recipe for target 'src/CMakeFiles/glfw.dir/all' failed
│ make[1]: *** [src/CMakeFiles/glfw.dir/all] Error 2
│ Makefile:129: recipe for target 'all' failed
│ make: *** [all] Error 2
│ [ Info: Downloading https://github.com/glfw/glfw/archive/3.3.tar.gz to /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/usr/downloads/src.tar.gz...
│ [ Info: Unpacking /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/usr/downloads/src.tar.gz into /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/usr/downloads/src
│ ┌ Warning: 
│ │ ================================================================
│ │ ================================================================
│ │ === Building GLFW has failed. Most common problem is,        ===
│ │ === that you don't have x-org installed.                     ===
│ │ === You can install it via: `sudo apt-get install xorg-dev`  ===
│ │ ================================================================
│ │ ================================================================
│ └ @ Main /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/build.jl:56
│ ERROR: LoadError: failed process: Process(`/builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/CMake/nSK2r/deps/usr/bin/cmake --build .`, ProcessExited(2)) [2]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│  [2] pipeline_error at ./process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
│  [4] run at ./process.jl:724 [inlined]
│  [5] (::getfield(Main, Symbol("##9#10")))() at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/build.jl:52
│  [6] cd(::getfield(Main, Symbol("##9#10")), ::String) at ./file.jl:96
│  [7] top-level scope at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/build.jl:43
│  [8] include at ./boot.jl:326 [inlined]
│  [9] include_relative(::Module, ::String) at ./loading.jl:1038
│  [10] include(::Module, ::String) at ./sysimg.jl:29
│  [11] include(::String) at ./client.jl:403
│  [12] top-level scope at none:0
│ in expression starting at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/deps/build.jl:21
│ [15:14:05] #=#=#                                                                         
[15:14:05] ##O#- #                                                                       
[15:14:06] ##O=#  #                                                                      
[15:14:06] #=#=-#  #                                                                     
[15:14:06] -#O#- #   #                                                                   
[15:14:06]  -#O#-  #   #                                                                 
[15:14:06]   -#O=#  #    #                                                               
[15:14:06] 
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
  Building GLMakie ─────────→ `/builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLMakie/8SH86/deps/build.log`
┌ Error: Error building `GLMakie`: 
│ ERROR: LoadError: GLFW not installed properly, run Pkg.build("GLFW"), restart Julia and try again
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/src/GLFW.jl:5
│  [3] include at ./boot.jl:326 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] top-level scope at none:2
│  [7] eval at ./boot.jl:328 [inlined]
│  [8] eval(::Expr) at ./client.jl:404
│  [9] top-level scope at ./none:3
│ in expression starting at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLFW/e257h/src/GLFW.jl:4
│ ERROR: LoadError: OpenGL/GLFW wasn't installed correctly. This likely means,
│ you don't have an OpenGL capable Graphic Card,
│ you don't have the newest video driver installed,
│ or the GLFW build failed. If you're on linux and `]build` GLFW failed,
│ try manually adding `sudo apt-get install libglfw3` and then `]build GLMakie`.
│ If you're on a headless server, you still need to install x-server and
│ proper GPU drivers. You can take inspiration from this article
│ on how to get Makie running on a headless system:
│ https://nextjournal.com/sdanisch/makie-1.0
│ If you don't have a GPU, there is also a Cairo software backend
│ for Makie which you can use:
│ https://github.com/JuliaPlots/CairoMakie.jl.
│ Please check the below error and open an issue at:
│ https://github.com/JuliaPlots/GLMakie.jl.
│ After you fixed your OpenGL install, please run `]build GLMakie` again!
│ GLMakie will still load, but will be disabled as a default backend for Makie
│ 
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLMakie/8SH86/deps/build.jl:28
│  [3] include at ./boot.jl:326 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:403
│  [7] top-level scope at none:0
│ in expression starting at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/GLMakie/8SH86/deps/build.jl:19
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
```

**Comment by SimonDanisch** [comment]
Ah... Woops, I may or may not have updated this to always be false: https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/test/runtests.jl#L6
Something wasn't working, and I was running out of time, so I just disabled the logic, since gitlab wasn't working for me anyways... Funny, that you get gitlab to actually run :D

**Comment by asinghvi17** [comment]
looking at the error...does Gitlab not have X?

**Comment by SimonDanisch** [comment]
It must be configured to use the runner setup by @maleadt!

**Comment by asinghvi17** [comment]
It is...this was running on `hydor.elis.ugent.be`, and shared runners have been disabled

**Comment by asinghvi17** [comment]
Also noticed that full tests were running...so fixed that

**Comment by SimonDanisch** [comment]
Ah, I haven;'t updated the gitlab CI script since it wasn't running for me....
It needs to be this nowadays: https://github.com/JuliaPlots/GLMakie.jl/blob/master/.gitlab-ci.yml

**Comment by asinghvi17** [comment]
If GLMakie builds properly on this, I'll reactivate `OPENGL`.

**Comment by SimonDanisch** [comment]
It should...Also all the other libraries aren't needed either ;)

**Comment by asinghvi17** [comment]
Interaction with mouse and color collection are failing.  It should be fine...

**Pull request merged**
