### PR TITLE
Add GR's `peaks` function

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
All examples are failing, and I'm not sure why.  @SimonDanisch I think something broke GLMakie?

**Comment by SimonDanisch** [comment]
Oh nice... I guess the master version of AbstractPlotting currently requires the master version of GLMakie

**Comment by SimonDanisch** [comment]
Lets tag it!

**Comment by asinghvi17** [comment]
Ah, is the new lighting stuff in?  Nice...we should write up a section in the backend page

**Comment by asinghvi17** [comment]
I'll merge this, and then let's tag!

**Comment by SimonDanisch** [comment]
GLMakie needs to be tagged first! It contains a non breaking change, to unbreak AbstractPlotting#master :P

**Comment by asinghvi17** [comment]
Ah, that makes sense...we should put a constraint in Makie also, in that case.

**Pull request merged**
