### PR TITLE
Remove tryrange

### PR DESCRIPTION
**Pull request by asinghvi17**
There's a blocking dispatch which is needed for StatsMakie, so `plot(sin)` can't work.  What I could do is `plot(automatic, sin)`, but that doesn't seem like a good API...

### CODE REVIEW

**Comment by asinghvi17** [comment]
This is the implementation I was going to use:
```julia
function convert_arguments(p::PointBased, ::Automatic, f::Function)
    xmin = tryrange(f, [-5,-1,0,0.01]) # establish a minimum where the function doesn't error
    xmax = tryrange(f, filter(x -> x > xmin, [5,1,0.99, 0, -0.01])) # same for a maximum

    return PlotUtils.adapted_grid(f, (xmin, xmax) # this returns (x, f.(x)) which goes through another convert
end
```

**Comment by SimonDanisch** [comment]
That looks like a good idea :)

**Comment by asinghvi17** [comment]
Will make another PR to implement that, then!

**Comment by SimonDanisch** [comment]
Thank you! :)

**Pull request closed without merging**
