### PR TITLE
rewrite text rendering

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Text rendering is one big chaos right now...
This, together with: https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/pull/30, should clean things up and fix #297 and help with better text rendering in CairoMakie

**Comment by asinghvi17** [comment]
Artifacts seem to be acting up quite a bit, so I expect we'll see random CI failures for a while.

**Comment by asinghvi17** [comment]
@SimonDanisch you might also want to rebase your PR on master...there seem to be some version incompatibilities.

**Comment by asinghvi17** [comment]
Would it be possible to have multiple fonts within the same "string", building off of this?  Italics and boldface, for example - especially in non-Unicode fonts - will be hard to implement without that.

**Comment by asinghvi17** [comment]
With the new branch, most of the examples work, but some are failing.  For example
```
 Running test_13
 MethodError: no method matching getindex(::FreeTypeAbstraction.FTFont)
 Stacktrace:
  [1] glyph_index!(::AbstractPlotting.TextureAtlas, ::Char, ::FreeTypeAbstraction.FTFont) at /builds/JuliaGPU/AbstractPlotting-jl/src/utilities/texture_atlas.jl:147
  [2] glyph_scale! at /builds/JuliaGPU/AbstractPlotting-jl/src/utilities/texture_atlas.jl:167 [inlined]
  [3] layout_text(::String, ::Point{2,Float32}, ::Float32, ::FreeTypeAbstraction.FTFont, ::Vec{2,Float32}, ::Quaternion{Float32}, ::SArray{Tuple{4,4},Float32,2,16}) at /builds/JuliaGPU/AbstractPlotting-jl/src/layouting/layouting.jl:21
  [4] (::AbstractPlotting.var"#386#388"{SArray{Tuple{4,4},Float32,2,16},Array{FreeTypeAbstraction.FTFont,1},Base.GenericIOBuffer{Array{UInt8,1}},Array{Point{3,Float32},1},Array{ColorTypes.RGBA{Float32},1},Array{Vec{2,Float32},1},Array{FreeTypeAbstraction.FTFont,1},Array{Quaternion{Float32},1}})(::Int64, ::Tuple{String,Point{2,Float32}}, ::ColorTypes.RGBA{Float32}, ::Float32, ::Vec{2,Float32}, ::Quaternion{Float32}) at /builds/JuliaGPU/AbstractPlotting-jl/src/basic_recipes/basic_recipes.jl:420
  [5] broadcast_foreach(::Function, ::UnitRange{Int64}, ::Vararg{Any,N} where N) at /builds/JuliaGPU/AbstractPlotting-jl/src/utilities/utilities.jl:173
  [6] (::AbstractPlotting.var"#385#387"{Array{Point{3,Float32},1},Array{ColorTypes.RGBA{Float32},1},Array{Vec{2,Float32},1},Array{FreeTypeAbstraction.FTFont,1},Array{Quaternion{Float32},1},Text{...}})(::SArray{Tuple{4,4},Float32,2,16}, ::Array{FreeTypeAbstraction.FTFont,1}, ::Array{Tuple{String,Point{2,Float32}},1}, ::Array{ColorTypes.RGBA{Float32},1}, ::Vararg{Any,N} where N) at /builds/JuliaGPU/AbstractPlotting-jl/src/basic_recipes/basic_recipes.jl:413
  [7] (::Observables.var"#g#15"{AbstractPlotting.var"#385#387"{Array{Point{3,Float32},1},Array{ColorTypes.RGBA{Float32},1},Array{Vec{2,Float32},1},Array{FreeTypeAbstraction.FTFont,1},Array{Quaternion{Float32},1},Text{...}},Tuple{Observables.Observable{Any},Observables.Observable{Any},Observables.Observable{Array{Tuple{String,Point{2,Float32}},1}},Observables.Observable{Any},Observables.Observable{Any},Observables.Observable{Any},Observables.Observable{Any}}})(::Array{Tuple{String,Point{2,Float32}},1}) at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/Observables/qCJWB/src/Observables.jl:136
  [8] #setindex!#1(::Observables.var"#2#4", ::typeof(setindex!), ::Observables.Observable{Array{Tuple{String,Point{2,Float32}},1}}, ::Array{Tuple{String,Point{2,Float32}},1}) at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/Observables/qCJWB/src/Observables.jl:87
  [9] setindex! at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/Observables/qCJWB/src/Observables.jl:83 [inlined]
  [10] notify!(::Observables.Observable{Array{Tuple{String,Point{2,Float32}},1}}) at /builds/JuliaGPU/AbstractPlotting-jl/src/interaction/nodes.jl:93
  [11] finish!(::Annotations{...}) at /builds/JuliaGPU/AbstractPlotting-jl/src/basic_recipes/buffers.jl:82
  [12] draw_axis2d(::Annotations{...}, ::LineSegments{...}, ::Tuple{LineSegments{...},LineSegments{...}}, ::Tuple{LineSegments{...},LineSegments{...}}, ::SArray{Tuple{4,4},Float32,2,16}, ::Float64, ::Tuple{Tuple{Int64,Int64},Tuple{Int64,Int64}}, ::Tuple{Tuple{Array{Float64,1},Array{Float64,1}},Tuple{Array{String,1},Array{String,1}}}, ::Tuple{Bool,Bool}, ::Tuple{Bool,Bool}, ::Tuple{Bool,Bool}, ::Tuple{Float64,Float64}, ::Tuple{Tuple{Symbol,Float64},Tuple{Symbol,Float64}}, ::Tuple{Nothing,Nothing}, ::Tuple{Int64,Int64}, ::Tuple{Tuple{Symbol,Float64},Tuple{Symbol,Float64}}, ::Tuple{Nothing,Nothing}, ::Tuple{Symbol,Symbol}, ::Tuple{Int64,Int64}, ::Tuple{Float64,Float64}, ::Tuple{Tuple{Symbol,Symbol},Tuple{Symbol,Symbol}}, ::Tuple{String,String}, ::Int64, ::Int64, ::Tuple{Int64,Int64}, ::Tuple{Tuple{Symbol,Float64},Tuple{Symbol,Float64}}, ::Tuple{Nothing,Nothing}, ::Tuple{Float64,Float64}, ::Float64, ::Symbol, ::Nothing, ::Nothing, ::Bool, ::Float64, ::Tuple{Tuple{Bool,Bool},Tuple{Bool,Bool}}, ::Tuple{String,String}, ::Tuple{Symbol,Symbol}, ::Tuple{Int64,Int64}, ::Tuple{Float64,Float64}, ::Tuple{Tuple{Symbol,Symbol},Tuple{Symbol,Symbol}}, ::Tuple{String,String}, ::Nothing) at /builds/JuliaGPU/AbstractPlotting-jl/src/basic_recipes/axis.jl:532
  [13] map_once(::Function, ::Observables.Observable{Annotations{...}}, ::Observables.Observable{LineSegments{...}}, ::Vararg{Observables.Observable,N} where N) at /builds/JuliaGPU/AbstractPlotting-jl/src/interaction/nodes.jl:83
  [14] plot!(::Scene, ::Type{Axis2D{...}}, ::Attributes, ::HyperRectangle{2,Int64}) at /builds/JuliaGPU/AbstractPlotting-jl/src/basic_recipes/axis.jl:582
  [15] #axis2d!#623 at /builds/JuliaGPU/AbstractPlotting-jl/src/recipes.jl:24 [inlined]
  [16] (::AbstractPlotting.var"#kw##axis2d!")(::NamedTuple{(:ticks, :raw),Tuple{NamedTuple{(:ranges, :labels),Tuple{Tuple{Array{Float64,1},Array{Float64,1}},Tuple{Array{String,1},Array{String,1}}}},Bool}}, ::typeof(axis2d!), ::Scene, ::HyperRectangle{2,Int64}) at ./none:0
 │   exception =
 │    LoadError: MethodError: no method matching getindex(::FreeTypeAbstraction.FTFont)
 │    in expression starting at test_13:5
 └ @ MakieGallery /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/ftcbf/src/database.jl:585
 with source:
     
     
         scene = Scene()
         cam2d!(scene)
         axis2d!(
             scene, IRect(Vec2f0(0), Vec2f0(1)),
             ticks = (
                 ranges = ([0.1, 0.2, 0.9], [0.1, 0.2, 0.9]),
                 labels = (["😸", "♡", "𝕴"], ["β ÷ δ", "22", "≙"])
             ), raw = true
         )
         center!(scene)
         scene
```
and some others, with the same `getindex(::FTFont)` not defined error.

Full job is here: https://gitlab.com/JuliaGPU/AbstractPlotting-jl/-/jobs/447011533

**Comment by SimonDanisch** [comment]
Continued in: https://github.com/JuliaPlots/AbstractPlotting.jl/pull/320

**Pull request closed without merging**
