### PR TITLE
updated doc for MakieLayout

### PR DESCRIPTION
**Pull request by norci**
make the doc easier to read.

see the comments in https://github.com/JuliaPlots/StatsMakie.jl/pull/129 .

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Thank you! I did some clarifications ;) I think there may have been some conflict with your force push, but seems like an acceptable version now.

**Comment by norci** [comment]
Great 👍 
The doc is much clearer.
Thanks for your help.

**Comment by SimonDanisch** [comment]
I think you removed the fork, so now I can't edit this pr nor fetch the commits/changes...
I had to make a new PR like here: https://github.com/JuliaPlots/AbstractPlotting.jl/pull/654
Let me know if it's ok to just merge that!
Going to close this PR, since it's impossible to merge like this!

**Comment by norci** [comment]
I'm sorry to say I deleted that fork too early.
thanks for your update.

**Pull request closed without merging**
