### PR TITLE
Correct typo in comment

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by mkborregaard** [comment]
He he it's easy to tell that we're reaching the end of October :-)

**Comment by eschnett** [comment]
What happens in October (or November)?

**Comment by mkborregaard** [comment]
Oh I was wrong :-)
You get a free hacktoberfest t-shirt if you make 10 github prs in October. Some PRs get very small :-)
https://hacktoberfest.digitalocean.com/

**Comment by eschnett** [comment]
Ooh. I'm sure there are some spaces that need adding, and then removing again. Thanks!

**Pull request merged**
