### PR TITLE
Towards a new version

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
I think we could also migrate from printing the name of the example to using ProgressMeter.jl, which will make output (hopefully) a lot cleaner.

**Comment by asinghvi17** [comment]
Test failures should reflect that `button` has been fixed, and that `cividis` has been added.

**Comment by asinghvi17** [comment]
```julia
colormap_collection: Error During Test at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/QyN7O/src/testruns.jl:97
  Got exception outside of a @test
  DimensionMismatch("A and B must have the same axes")
  Stacktrace:
   [1] sumdiff(::typeof(abs), ::Array{ColorTypes.RGB{Float64},2}, ::Array{ColorTypes.RGB{Float64},2}) at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/QyN7O/src/visualregression.jl:81
   [2] sad(::Array{ColorTypes.RGB{Float64},2}, ::Array{ColorTypes.RGB{Float64},2}) at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/QyN7O/src/visualregression.jl:95
   [3] approx_difference(::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}, ::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}, ::Array{Int64,1}, ::Float64) at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/QyN7O/src/visualregression.jl:111
   [4] #compare_media#127(::Array{Int64,1}, ::Float64, ::Function, ::String, ::String) at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/QyN7O/src/testruns.jl:51
   [5] compare_media(::String, ::String) at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/QyN7O/src/testruns.jl:47
   [6] macro expansion at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/QyN7O/src/testruns.jl:104 [inlined]
   [7] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083 [inlined]
   [8] macro expansion at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/QyN7O/src/testruns.jl:98 [inlined]
   [9] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083 [inlined]
   [10] #run_comparison#130(::Float64, ::Function, ::String, ::String, ::String) at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/QyN7O/src/testruns.jl:85
   [11] run_comparison at /builds/JuliaGPU/AbstractPlotting-jl/.julia/packages/MakieGallery/QyN7O/src/testruns.jl:84 [inlined] (repeats 2 times)
```
This test failure is non-trivial.

**Comment by SimonDanisch** [comment]
You need GLMakie#sd-new_version!

**Comment by asinghvi17** [comment]
Button clicking seems to not be working for me.

**Comment by asinghvi17** [comment]
Haven't pushed these commits yet, but I've done a minor refactoring of AbstractPlotting to use FFMPEG.jl.

**Comment by asinghvi17** [comment]
```julia
running animated_time_series
ERROR: LoadError: IOError: open: no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error at ./libuv.jl:90 [inlined]
 [2] open(::String, ::UInt16, ::Int64) at ./filesystem.jl:81
 [3] open at ./filesystem.jl:73 [inlined]
 [4] sendfile(::String, ::String) at ./file.jl:751
 [5] #cp#12(::Bool, ::Bool, ::typeof(cp), ::String, ::String) at ./file.jl:336
 [6] #cp at ./none:0 [inlined]
 [7] rename(::String, ::String) at ./file.jl:740
 [8] #mv#13 at ./file.jl:378 [inlined]
 [9] #mv at ./none:0 [inlined]
 [10] save_media(::MakieGallery.CellEntry, ::String, ::String) at /Users/anshul/.julia/dev/MakieGallery/src/io.jl:10
 [11] (::getfield(MakieGallery, Symbol("##103#105")){Tuple{Int64,Int64},String,Array{Any,1}})(::MakieGallery.CellEntry, ::String) at /Users/anshul/.julia/dev/MakieGallery/src/io.jl:221
 [12] (::getfield(MakieGallery, Symbol("##78#79")){Base.Iterators.Pairs{Symbol,getfield(MakieGallery, Symbol("#output_path#104")){String},Tuple{Symbol},NamedTuple{(:outputfile,),Tuple{getfield(MakieGallery, Symbol("#output_path#104")){String}}}},getfield(MakieGallery, Symbol("##103#105")){Tuple{Int64,Int64},String,Array{Any,1}}})(::MakieGallery.CellEntry) at /Users/anshul/.julia/dev/MakieGallery/src/database.jl:572
 [13] #enumerate_examples#61(::Int64, ::Nothing, ::typeof(MakieGallery.enumerate_examples), ::getfield(MakieGallery, Symbol("##78#79")){Base.Iterators.Pairs{Symbol,getfield(MakieGallery, Symbol("#output_path#104")){String},Tuple{Symbol},NamedTuple{(:outputfile,),Tuple{getfield(MakieGallery, Symbol("#output_path#104")){String}}}},getfield(MakieGallery, Symbol("##103#105")){Tuple{Int64,Int64},String,Array{Any,1}}}) at /Users/anshul/.julia/dev/MakieGallery/src/database.jl:503
 [14] #enumerate_examples at ./none:0 [inlined]
```
is the issue I'm consistently getting.  It looks like the file is not saved in the first place.  Could it be something to do with `withenv`?

**Comment by asinghvi17** [comment]
OK, bug is fixed locally.  Pushing the commit now...

**Comment by asinghvi17** [comment]
Bug with printing plots of a Scene:
```julia
scene.plots
2-element Array{AbstractPlot,1}:
 Error showing value of type Array{AbstractPlot,1}:
ERROR: ArgumentError: can't repeat a string -8 times
Stacktrace:
 [1] repeat(::String, ::Int64) at ./strings/substring.jl:195
 [2] print_matrix_row(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{AbstractPlot,1}, ::Array{Tuple{Int64,Int64},1}, ::Int64, ::UnitRange{Int64}, ::String) at ./arrayshow.jl:110
 [3] print_matrix(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{AbstractPlot,1}, ::String, ::String, ::String, ::String, ::String, ::String, ::Int64, ::Int64) at ./arrayshow.jl:192
 [4] print_matrix at ./arrayshow.jl:159 [inlined]
 [5] print_array at ./arrayshow.jl:308 [inlined]
 [6] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::Array{AbstractPlot,1}) at ./arrayshow.jl:345
 [7] display(::REPL.REPLDisplay, ::MIME{Symbol("text/plain")}, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:132
 [8] display(::REPL.REPLDisplay, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:136
 [9] display(::Any) at ./multimedia.jl:323
 [10] (::getfield(Media, Symbol("##15#16")){Array{AbstractPlot,1}})() at /Users/anshul/.julia/packages/Media/ItEPc/src/compat.jl:28
 [11] hookless(::getfield(Media, Symbol("##15#16")){Array{AbstractPlot,1}}) at /Users/anshul/.julia/packages/Media/ItEPc/src/compat.jl:14
 [12] render(::Media.NoDisplay, ::Array{AbstractPlot,1}) at /Users/anshul/.julia/packages/Media/ItEPc/src/compat.jl:27
 [13] render(::Array{AbstractPlot,1}) at /Users/anshul/.julia/packages/Media/ItEPc/src/system.jl:160
 [14] display(::Media.DisplayHook, ::Array{AbstractPlot,1}) at /Users/anshul/.julia/packages/Media/ItEPc/src/compat.jl:9
 [15] display(::Any) at ./multimedia.jl:323
 [16] #invokelatest#1 at ./essentials.jl:790 [inlined]
 [17] invokelatest at ./essentials.jl:789 [inlined]
 [18] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:156
 [19] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:141
 [20] (::getfield(REPL, Symbol("#do_respond#38")){Bool,getfield(REPL, Symbol("##48#57")){REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:718
 [21] #invokelatest#1 at ./essentials.jl:790 [inlined]
 [22] invokelatest at ./essentials.jl:789 [inlined]
 [23] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2306
 [24] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:1038
 [25] run_repl(::REPL.AbstractREPL, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:201
 [26] (::getfield(Base, Symbol("##737#739")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:390
 [27] #invokelatest#1 at ./essentials.jl:790 [inlined]
 [28] invokelatest at ./essentials.jl:789 [inlined]
 [29] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:374
 [30] exec_options(::Base.JLOptions) at ./client.jl:312
 [31] _start() at ./client.jl:464
```

**Pull request merged**
